### ISSUE TITLE
Normalization or standardization? Chapter 10

### ISSUE THREAD

**Issue by akuyper** [moderndive/moderndive_book#121]
Maybe consider using standardization in place of normalization. 

In my experience, it is common for students (and researchers) to mistakenly believe that normalization implies they are making the variable/data normal when in fact they are simply transforming their variable/data to a standard scale.

Just as the standard error is a special type of standard deviation, standardization can be thought of as a special type of normalization. It is such an important type that it gets its own name.

Section 10.8.1: 

> What is commonly done in statistics is the process of normalization. What this entails is calculating the mean and standard deviation of a variable. Then you subtract the mean from each value of your variable and divide by the standard deviation. The most common normalization is known as the z-score

**Comment by ismayc** [comment]
Thanks! I like that language better as well, especially since we head into t-scores soon after. Change has been made [here](https://github.com/moderndive/moderndive_book/commit/ab38a8ed6ce738d5e967674027831393147a1e13) and will be reflected in the next formal update of the book at moderndive.com. The development version of the book at https://moderndive.netlify.com will have the updated language in a few minutes after the book rebuilds.
