### ISSUE TITLE
Broken Link - page 1: link to pdf

### ISSUE THREAD

**Issue by AlishaAdrian** [moderndive/moderndive_book#175]
While a PDF version of this book can be found here, this is very much a work in progress with many things that still need to be fixed. We appreciate your patience. 

The word "here" in this sentence is a link, but it is broken. I would really love to have a pdf version as I have issues reading an electronic device. 

Thanks!

**Comment by rudeboybert** [comment]
Thanks for this, we're currently updating the book a bit so we'll fix the link afterwards. In the meanwhile, here is a link to the PDF: https://drive.google.com/file/d/1lqMWVhd8VRuE3JPDp91YGEr-AernLjs-/view

**Comment by rudeboybert** [comment]
@ismayc Instead of copying the PDF to Google Drive using the script in `copy_pdf_to_google_drive.R`, could we do the following?

1. Have the pdf output to `moderndive.pdf` (in the repo root, also with more obvious name) instead of `dosc/ismaykim.pdf`?
1. In `index.Rmd` add the following code that will copy it to `docs/`: `file.copy("moderndive.pdf", "docs/moderndive.pdf", overwrite = TRUE)`

That way people can access the PDF at <https://moderndive.com/moderndive.pdf> as well as <https://moderndive.netlify.com/moderndive.pdf>. Because as it currently stands, when travis builds the book and deploys to the gh-pages branch, somehow the PDF disappears: https://github.com/moderndive/moderndive_book/tree/gh-pages

**Comment by ismayc** [comment]
Travis doesn’t do the PDF build so we’d need to figure out a way to get a LaTeX compiler to run on the travis instance. We can manually build the PDF and move it there but it isn’t automated.

**Comment by rudeboybert** [comment]
I'm ok not having the PDF build be automated. We can do that manually only with every update to moderndive.com i.e. every 6 months.

**Comment by rudeboybert** [comment]
Heads up that code to this effect seems to already exist: https://github.com/moderndive/moderndive_book/blob/master/index.Rmd#L139

**Comment by rudeboybert** [comment]
Hi @AlishaAdrian, we've fixed things whereby you can access the PDF at <https://moderndive.com/moderndive.pdf>. Also the "here" link you originally mentioned has been fixed.

Note: we updated moderndive.com to v0.6.0 yesterday. The biggest changes are improvements to Chapters 9-11 on statistical inference. 

thanks for bringing this issue to our attention!
