### ISSUE TITLE
Fix links to previous versions in Section 1.4

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive_book#23]
Currently they read from Hostgator folder `previous_versions`

**Comment by ismayc** [comment]
Might be best to use `source()` similar to what is done in https://github.com/moderndive/moderndive_book/blob/master/_build.sh to copy the `previous_versions` folder into `docs`. Could use `file.copy(recursive = TRUE)` to move them from a stable location outside of `docs` in after the `purl` scripts are run in `_build.sh` via travis. Or if that's too much of a pain, we could just manually copy over the previous versions into `docs` since we don't increment versions that often.

**Comment by rudeboybert** [comment]
Merged into #32
