### ISSUE TITLE
"All checks have failed" when submitting the pull request to ModernDive

### ISSUE THREAD

**Issue by xiaochi-liu** [moderndive/ModernDive_book#407]
Thanks to this masterpiece, I finally have a deep understanding of statistical inference. Thank you very much!

As I read through this book, I spotted some typos or errors, and I proposed to edit it via GitHub Pull Request. However, there are always messages telling me some checks have failed, such as the status shown in the following screenshot:

![image](https://user-images.githubusercontent.com/48895627/103511333-f8ccff80-4eba-11eb-965b-486dfb87be93.png)

What does it mean? Can you see the pull request I made?

![image](https://user-images.githubusercontent.com/48895627/103614277-583f1400-4f7c-11eb-8b61-42ba3625a3b7.png)

Many thanks for your kind guidance.

**Comment by rudeboybert** [comment]
Hey @xiaochi-liu, thanks for your PR's. The issue is that this repo uses Travis for continuous integration (like testing whether code changes in PR's are valid). The R community has encouraged people to move away from Travis CI to GitHub actions (see this [blogpost](https://ropensci.org/technotes/2020/11/19/moving-away-travis/)). We *might* make this switch, but given how infrequently we update this repo given that its content is stable, it might not be worth the time.
