### ISSUE TITLE
An incomplete list of unlinked tables

### ISSUE THREAD

**Issue by apreshill** [moderndive/moderndive_book#62]
`Comparison: Let’s compare the 3 standard errors we computed above in Table ??:`
- https://moderndive.com/8-sampling.html#using-different-shovels

`We present a wide array of such scenarios in Table ??.`
- https://moderndive.com/9-confidence-intervals.html

Will add more as I find them.

**Comment by rudeboybert** [comment]
Thanks @apreshill, we'll fix shortly!

**Comment by rudeboybert** [comment]
Quoting @ismayc: It looks like the issues with the `kable` tables not linking in the later part of the book are due to the wrapper functions in `moderndive`. When I move chapters 6 and 7 to the end of the book, the problems go away. We might want to remove `kable()` from `moderndive` entirely to test it out.

**Comment by ismayc** [comment]
There's something even stranger here since after I removed all of the `kable()` references from the `moderndive` package, the ?? are still showing up in 5 pages of the PDF. I'm gonna have to pass this one back to you, @rudeboybert, as I am out of ideas. It's going to have to take a lot of slow additions and subtractions to figure out exactly what is causing the problems here.

**Comment by ismayc** [comment]
Fixed in #70
